# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{clamsy}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["NgTzeYang"]
  s.date = %q{2010-05-04}
  s.description = %q{}
  s.email = %q{ngty77@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "HISTORY.txt",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "clamsy.gemspec",
     "clamsy.png",
     "lib/clamsy.rb",
     "lib/clamsy.yml",
     "lib/clamsy/base_printer.rb",
     "lib/clamsy/configuration.rb",
     "lib/clamsy/cups_pdf_printer.rb",
     "lib/clamsy/file_system_support.rb",
     "lib/clamsy/template_open_doc.rb",
     "lib/clamsy/tenjin.rb",
     "spec/clamsy/base_printer_spec.rb",
     "spec/clamsy/configuration_spec.rb",
     "spec/clamsy/cups_pdf_printer_spec.rb",
     "spec/clamsy/data/clamsy.png",
     "spec/clamsy/data/clamsy2.png",
     "spec/clamsy/data/embedded_ruby_after.odt",
     "spec/clamsy/data/embedded_ruby_before.odt",
     "spec/clamsy/data/escaped_text_after.odt",
     "spec/clamsy/data/escaped_text_before.odt",
     "spec/clamsy/data/invalid_content_example.odt",
     "spec/clamsy/data/invalid_zip_example.odt",
     "spec/clamsy/data/multiple_contexts_after.odt",
     "spec/clamsy/data/multiple_contexts_before.odt",
     "spec/clamsy/data/picture_after.odt",
     "spec/clamsy/data/picture_before.odt",
     "spec/clamsy/data/plain_text_after.odt",
     "spec/clamsy/data/plain_text_before.odt",
     "spec/clamsy/file_system_support_spec.rb",
     "spec/clamsy/invalid_printer_spec.rb",
     "spec/clamsy/template_open_doc_spec.rb",
     "spec/integration/cups_pdf_printer_spec.rb",
     "spec/integration/data/embedded_ruby_example.odt",
     "spec/integration/data/embedded_ruby_example.pdf",
     "spec/integration/data/escaped_text_example.odt",
     "spec/integration/data/escaped_text_example.pdf",
     "spec/integration/data/multiple_contexts_example.odt",
     "spec/integration/data/multiple_contexts_example.pdf",
     "spec/integration/data/norm_clamsy.png",
     "spec/integration/data/picture_example.odt",
     "spec/integration/data/picture_example.pdf",
     "spec/integration/data/plain_text_example.odt",
     "spec/integration/data/plain_text_example.pdf",
     "spec/integration/data/sunny_clamsy.png",
     "spec/integration/has_stardand_integration_support_shared_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/ngty/clamsy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A clumsily shellish way to generate a single pdf for multiple contexts from an odt template}
  s.test_files = [
    "spec/integration/cups_pdf_printer_spec.rb",
     "spec/integration/has_stardand_integration_support_shared_spec.rb",
     "spec/clamsy/file_system_support_spec.rb",
     "spec/clamsy/base_printer_spec.rb",
     "spec/clamsy/cups_pdf_printer_spec.rb",
     "spec/clamsy/invalid_printer_spec.rb",
     "spec/clamsy/configuration_spec.rb",
     "spec/clamsy/template_open_doc_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubyzip>, ["= 0.9.4"])
      s.add_runtime_dependency(%q<rghost>, ["= 0.8.7.2"])
      s.add_runtime_dependency(%q<nokogiri>, ["= 1.4.1"])
      s.add_development_dependency(%q<bacon>, [">= 1.1.0"])
    else
      s.add_dependency(%q<rubyzip>, ["= 0.9.4"])
      s.add_dependency(%q<rghost>, ["= 0.8.7.2"])
      s.add_dependency(%q<nokogiri>, ["= 1.4.1"])
      s.add_dependency(%q<bacon>, [">= 1.1.0"])
    end
  else
    s.add_dependency(%q<rubyzip>, ["= 0.9.4"])
    s.add_dependency(%q<rghost>, ["= 0.8.7.2"])
    s.add_dependency(%q<nokogiri>, ["= 1.4.1"])
    s.add_dependency(%q<bacon>, [">= 1.1.0"])
  end
end

